### ISSUE TITLE
Would you consider give each point a weight?

### ISSUE THREAD

**Issue by hitdshu** [terzakig/sqpnp#4]
Hi,

Thanks for your excellent work. Currently, this repo minimizes (sum_i squared_error_of_i). 

I have some applications that need to add weight to each squared_error_of_i. So that the final cost is (sum_i squared_error_of_i * weight_of_i). Could you please consider give each point a weight in current implementation? I tried myself, but since I did not understand your method fully, I couldn't get meaningful results...

Best,
Deshun

**Comment by terzakig** [comment]
Hi there, thanks for bringing this up and thanks for your interest in the work. Yes, an optional weight vector is an important feature. Will be adding it, please allow a few days.

**Comment by hitdshu** [comment]
> Hi there, thanks for bringing this up and thanks for your interest in the work. Yes, an optional weight vector is an important feature. Will be adding it, please allow a few days.

Thanks for your very timely and kind reply. Actually, I would like to use your excellent code together with graduated non-convex, so I could deal with a large number of outliers combining deterministic annealing and non-minimal solver. 

Have a nice day.
Deshun

**Comment by terzakig** [comment]
> > Hi there, thanks for bringing this up and thanks for your interest in the work. Yes, an optional weight vector is an important feature. Will be adding it, please allow a few days.
> 
> Thanks for your very timely and kind reply. Actually, I would like to use your excellent code together with graduated non-convex, so I could deal with a large number of outliers combining deterministic annealing and non-minimal solver.
> 
> Have a nice day. Deshun

Hi Deshun,

You should now be able to pass weights for your PnP residuals in the solver's constructor (see new argument `_weights`). Note that the changes have not yet been merged with master, so you need to checkout the `add_weights` branch. 

I believe the changes are working nicely, but feel free to report any problems you may encounter here. I will leave the issue open for a  few days and then merge the branch with master.

All the best with your work.

**Comment by hitdshu** [comment]
> > > Hi there, thanks for bringing this up and thanks for your interest in the work. Yes, an optional weight vector is an important feature. Will be adding it, please allow a few days.
> > 
> > 
> > Thanks for your very timely and kind reply. Actually, I would like to use your excellent code together with graduated non-convex, so I could deal with a large number of outliers combining deterministic annealing and non-minimal solver.
> > Have a nice day. Deshun
> 
> Hi Deshun,
> 
> You should now be able to pass weights for your PnP residuals in the solver's constructor (see new argument `_weights`). Note that the changes have not yet been merged with master, so you need to checkout the `add_weights` branch.
> 
> I believe the changes are working nicely, but feel free to report any problems you may encounter here. I will leave the issue open for a few days and then merge the branch with master.
> 
> All the best with your work.

Many thanks for your very kind and very fast help. You did it much faster than I thought. I'll use your updated code this weekend. I appreciate your support very much.

Best regards,
Deshun

**Comment by hitdshu** [comment]
I think there might be a small problem with current implementation.   I changed all the weights in your provided example as 0.1, and the result is not right...

https://github.com/terzakig/sqpnp/blob/add_weights/sqpnp/sqpnp.h#L96

I changed the code here from 
```c++
const double wx = projections_.rbegin()->vector[0],
               wy = projections_.rbegin()->vector[1], 
```
to
```
const double wx = projections_.rbegin()->vector[0] * w,
               wy = projections_.rbegin()->vector[1] * w, 
```
, now the code works..

Deshun

**Comment by terzakig** [comment]
Yes, you are correct! Thanks a lot for spotting this! I have already pushed a fix.

**Comment by hitdshu** [comment]
Thanks for your very timely ans kind reply. However, I still have some problems when using your code together with graduated non-convex. Your code is very fine, it's just look like the two algorithms do not fit well...

1. As I'm dealing with a lot of outliers by graduated weighting them, sometimes the SQPNP returns two solutions. Which one should I select? Choosing the wrong one cause a disaster for the graduated algorithm...
2. Another problem relates to the numerics. Sometimes, the SQPNP algorithm terminates here https://github.com/terzakig/sqpnp/blob/add_weights/sqpnp/sqpnp.cpp#L352 The index1 is -1 here.....It looks like a numeric issue, because there are a large number of outliers in the input...

It would be very kind of you if you could provide some cues for the two problems.

Best,
Deshun

**Comment by hitdshu** [comment]
Again, thanks for your excellent work. And thanks for your kindness for helping with this

**Comment by terzakig** [comment]
Hi,

I am assuming that you have sufficiently enough points, i.e., n >> 4. If this is so, both 1 and 2 are a result of poorly conditioned data matrix. I am guessing that your weights become very close to zero at some step of the process, thereby causing the instability. In particular 1) if you have multiple solutions it means that the problem, possibly due to weighting, is equivalent to a P3P, P4P, P6P or P7P, which is something you should not expect for n >> 4, even with weights. About (2), you probably get an an even more ill-conditioned problem setup ( I would assume that manifests shortly after you have seen multiple solutions).

I think you need to work on the GNC starting values and make sure you terminate in time. Also, albeit less likely, there could be something wrong with the data, causing the process to lower the weights drastically.

**Comment by hitdshu** [comment]
Thanks for your comments. The algorithm does converge to the solution if the initial transform is close to the ground truth. And as you commented, it has numeric issure when the initial transform is far from the ground truth. The weights are just too small in the second case....

I'll close the issue. Thanks very much for your help.
